### ISSUE TITLE
Very_first_issue

### ISSUE THREAD

**Issue by ChuUser** [ChuUser/testNewaddress#1]
very first issue

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xe6b314b98d5b29bde8bf52e21b768233500a8ec4b8246362cdbae91331e18f3c](https://ropsten.etherscan.io/tx/0xe6b314b98d5b29bde8bf52e21b768233500a8ec4b8246362cdbae91331e18f3c)
